@baseUrl = http://localhost:3000


### Buscar todos recados
# @name recadosAll
GET {{baseUrl}}/recados

### 

### Buscar um recado por id
# @name recadosFindOne
GET {{baseUrl}}/recados/1

### Criar Recados
# @name recadosPost
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Este eh um recado de teste 3",
    "de": "Ramon",
    "para": "miguel"
}

### Atualiza um recado
# @name atualizarRecado
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
    "texto": "Este eh um recado de teste modificado 9090",
    "lido": false

}


### Deletar usuario
# @name deletarTarefa
DELETE {{baseUrl}}/recados/5