@baseUrl = http://localhost:3000


### Buscar todos recados
# @name recadosAll
GET {{baseUrl}}/recados

### 

### Buscar um recado por id
# @name recadosFindOne
GET {{baseUrl}}/recados/2

### Criar Recados
# @name recadosPost
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Este eh um recado de teste 3",
    "de": "Ramon",
    "para": "miguel",
    "lido": false,
    "data": "2026-05-30T14:31:14.493Z"
}

### Atualiza um recado
# @name atualizarRecado
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

{
    "texto": "Este eh um recado de teste modificado 233",
    "de": "Jonatas",
    "para": "miguel",
    "lido": false,
    "data": "2026-05-30T14:31:14.493Z"
}


### Deletar usuario
# @name deletarTarefa
DELETE {{baseUrl}}/recados/1